---
- name: Configuration complète de l'environnement pour WordPress
  hosts: all
  become: true

  roles:
    - prepare_docker
    - prepare_http_server
    - prepare_php
    - prepare_db_server
    - prepare_wordpress
    - setup_tls_certbot

  vars:
    ansible_python_interpreter: /usr/bin/python3
