---
- name: Installer Apache2
  ansible.builtin.apt:
    name: apache2
    state: present
    update_cache: yes

- name: Activer mod_rewrite
  ansible.builtin.command: a2enmod rewrite
  become: true
  notify:
    - Redémarrer Apache2

- name: Activer mod_http2
  ansible.builtin.command: a2enmod http2
  become: true
  notify:
    - Redémarrer Apache2

- name: Assurer que le service Apache2 est actif
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: yes

- name: Redémarrer Apache pour appliquer les changements
  ansible.builtin.systemd:
    name: apache2
    state: restarted
    enabled: yes
  become: true
  when: ansible_facts['distribution'] == "Ubuntu"
